### ISSUE TITLE
NHS trust - LTLA link

### ISSUE THREAD

**Issue by AdeleW** [VictimOfMaths/COVID-19#7]
Hi,

Great work - your charts are super interesting and informative!

How do you link NHS trusts with LTLAs? Is it a one to one assignment or by proportions? Please could you refer me to the script/resource used for this?

Thanks,

Adele

**Comment by VictimOfMaths** [comment]
Thanks Adele,

I use an approach developed by Ben Barr at Liverpool, where he uses the % of admissions in previous years to each trust which originated  in different LAs. So if in a given trust in pre-COVID years saw 50% of its admissions come from one LTLA and 50% from another, we apportion 50% of the COVID-era admissions to each of those LTLAs.

It's a bit complicated in practice because of NHS trust mergers and the fact that the published admissions and deaths data use slightly different lists of trusts (and the admissions data includes a trust merger in the middle of it).

Simpler code for the deaths data is here from line 50 onwards https://github.com/VictimOfMaths/COVID-19/blob/master/Heatmaps/English%20LA%20Heatmaps.R

And comprehensive code for both admissions and deaths is here from line 464 onwards https://github.com/VictimOfMaths/COVID_LA_Plots/blob/master/UnderlyingCode.R

Hope that helps.

Colin
